---
- name: Gether Os Facts
  hosts: my_vms
  gather_facts: true
  
  tasks:
    - name: Print Os Details
      debug:
        var: ansible_facts
      
    - name: Print Username
      debug:
        var: ansible_facts.user_id
      
    
    - name: Save Os Details
      copy:
        content: "{{ ansible_facts }}"
        dest: "/{{ ansible_facts.user_dir }}/{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version}}.txt"
      
