---
- name: Gather OS facts
  include_tasks: os_info_tasks.yml

- name: Create file with OS info
  file:
    path: "/home/{{ ansible_user }}/os_info.txt"
    state: touch

- name: Save OS details to file
  lineinfile:
    line: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"
    path: "/home/{{ ansible_user }}/os_info.txt"

